name: First Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  boo:

    runs-on: ubuntu-${{ ubuntu-version }}

    steps:
      - name: Print working directory
        run: pwd

      - name: List all web projects
        run: ls /var/www/html

      - name: Execute a series of commands
        run: |
          echo "one"
          echo "two"
          echo "three four five"
          echo "once I caught a fish alive"

